local wait = require("runLater")
local syncedSlash = false
local slash
local emoji
local emojiBool
local emojiStored
local chatVis
local chatCheck
local chatText
local textVisibility = 0
local textPosCorrect

local ValidEmojis = {
    "blahaj","shark","plush_shark",
    "blahaj2","shark2","plush_shark2",
    "shrimp",
    "crab",
    "lobster",
    "lobster2","lobster_blue",
    "octopus",
    "squid",
    "whale",
    "turtle",
    "axolotl",
    "blowfish", "pufferfish", "guh",
    "tropical_fish", "clownfish",
    "fish",
    "jelly", "jellyfish",
    "seahorse",
    "moth",
    "butterfly",
    "bee",
    "snail",
    "snake", "snek",
    "bat",
    "bug",
    "cat",
    "cat2", "cat-black",
    "wolf",
    "fox",
    "mouse", "rat", "lab_rat",
    "pig",
    "cow",
    "egg_hatch", "baby_chicken_hatch",
    "chick", "baby_chicken",
    "sheep",
    "rabbit", "bunny",
    "dragon",
    "penguin", "linux",
    "cat3", "gray_cat", "osu_cat", "plush_cat",
    "giraffe_head", "giraffe1", "giraffe",
    "giraffe_neck", "giraffe2",
    "giraffe_body", "giraffe3",
    "slime", "blob", "boinger",
    "skull_4", "skull_rotate",
    "banana_rotata_x",
    "banana_rotata_y",
    "banana_rotata_z",
    "tbh_squish",
    "heart_rainbow", "rainbow_heart",
    "slime_boing", "slime_bounce", "boing", "slime_gang",
    "triumph",
    "mad", "mad1",
    "angered", "rage",
    "censored", "swearing",
    "screaming", "shouting",
    "mad2",
    "mad3",
    "biba_annoyed",
    "biba_sunglasses",
    "biba_cry",
    "biba_angry",
    "biba_smile",
    "biba_shocked",
    "biba_happy",
    "biba_squint",
    "biba_yawn",
    "biba_yum",
    "biba_blush",
    "biba_worried",
    "biba_love",
    "biba_unamused",
    "biba_dizzy",
    "biba_eyebrow",
    "biba_wink",
    "biba_big_smile",
    "biba_perplexed",
    "biba_woozy",
    "biba_confused",
    "biba_stern",
    "biba_furious",
    "biba_sleepy",
    "scream",
    "scream_cat",
    "oh", "open_mouth",
    "wow", "gasp",
    "dizzy", "stroke",
    "exploding_head",
    "fake_dead1", "bleh","crossed_eyes",
    "heated", "hot_face",
    "smile", "smile1",
    "smile_big", "smile2",
    "smile_happy", "smile3",
    "blush",
    "innocent", "angel",
    "holding_back_tears",
    "star_struck", "starry_eyes",
    "celebration", "partying_face",
    "sunglasses", "cool",
    "money_mouth", "rich",
    "wink", ";3",
    "pleased",
    "heart_eyes",
    "blow_kiss",
    "kiss",
    "uwu",
    "owo",
    "uwu_eager",
    "pleading",
    "yum",
    "silly",
    "silly_wink",
    "sheesh", "flirty",
    "smile+1",
    "yawn", "uninterested", "distracted",
    "o7", "salute",
    "sleeping", "sleepy", "kiri",
    "freezing",
    "nerd", "gs",
    "clown", "bozo",
    "smiling_imp",
    "money_machine", "mr_krabs",
    "alien", "51",
    "swagger", "cowboy",
    "mlg",
    "anime_glasses",
    "blue_emoji",
    "skill_issue",
    "eyes",
    "skull", '💀',
    "anonymous", "guy_fawkes",
    "ghost",
    "ayo", "pull_down_sunglasses",
    "incognito",
    "flushed",
    "woozy",
    "confounded",
    "thinking", "thinkies", "think",
    "upside_down", "australia",
    "huh", "eyebrow",
    "hmm", "raised_eyebrow",
    "monocle",
    "shh", "shush",
    "confused1", "what",
    "woozy_melt",
    "melt", "blob",
    "sweat_smile",
    "sweat",
    "blank", "no_mouth",
    "neutral_face",
    "zipper", "zipper_mouth",
    "confused",
    "hand_over_mouth",
    "damn", "grimacing",
    "liar", "pinocchio",
    "head_in_clouds",
    "bandage_head", "injured",
    "mask", "bovid", "lovid", "covid", "david",
    "sick", "fever",
    "nausea",
    "nauseous", "holding_back_vomit",
    "vomit",
    "rolling_eyes",
    "annoyed", "exhale",
    "expressionless", "closed_eyes","neutral",
    "diagonal_mouth",
    "really?", "disappointed",
    "disgusted", "drama",
    "persevere",
    "pensive",
    "unamused",
    "frown", "sad",
    "shocked",
    "guilty",
    "tear_smile",
    "tear_frown",
    "worry",
    "tear_worry",
    "ashamed",
    "distraught",
    "sob",
    "crying_loudly",
    "crying_pancake",
    "fake_dead",
    "despair",
    "exhausted", "leave_me_alone",
    "judging", "stare",
    "tongue_wink", "mocking",
    "zany", "drunk",
    "goofy",
    "lmao",
    "flag_ad","andorra",
    "flag_ae","united_arab_emirates",
    "flag_af","afghanistan",
    "flag_ag","antigua_and_barbuda",
    "flag_ai","anguilla",
    "flag_al","albania",
    "flag_am","armenia",
    "flag_ao","angola",
    "flag_aq","antarctica",
    "flag_ar","argentina",
    "flag_as","american_samoa",
    "flag_at","austria",
    "flag_au","australia",
    "flag_aw","aruba",
    "flag_ax","åland_islands",
    "flag_az","azerbaijan",
    "flag_ba","bosnia_and_herzegovina",
    "flag_bb","barbados",
    "flag_bd","bangladesh",
    "flag_be","belgium",
    "flag_bf","burkina_faso",
    "flag_bg","bulgaria",
    "flag_bh","bahrain",
    "flag_bi","burundi",
    "flag_bj","benin",
    "flag_bl","saint_barthélemy",
    "flag_bm","bermuda",
    "flag_bn","brunei_darussalam",
    "flag_bo","bolivia",
    "flag_bq","bonaire,_sint_eustatius_and_saba",
    "flag_br","brazil",
    "flag_bs","bahamas",
    "flag_bt","bhutan",
    "flag_bv","bouvet_island",
    "flag_bw","botswana",
    "flag_by","belarus",
    "flag_bz","belize",
    "flag_ca","canada",
    "flag_cc","cocos_(keeling)_islands",
    "flag_cd","congo",
    "flag_cf","central_african_republic",
    "flag_cg","congo",
    "flag_ch","switzerland",
    "flag_ci","côte_d'ivoire",
    "flag_ck","cook_islands",
    "flag_cl","chile",
    "flag_cm","cameroon",
    "flag_cn","china",
    "flag_co","colombia",
    "flag_cr","costa_rica",
    "flag_cu","cuba",
    "flag_cv","cape_verde",
    "flag_cw","curaçao",
    "flag_cx","christmas_island",
    "flag_cy","cyprus",
    "flag_cz","czech_republic",
    "flag_de","germany",
    "flag_dj","djibouti",
    "flag_dk","denmark",
    "flag_dm","dominica",
    "flag_do","dominican_republic",
    "flag_dz","algeria",
    "flag_ec","ecuador",
    "flag_ee","estonia",
    "flag_eg","egypt",
    "flag_eh","western_sahara",
    "flag_er","eritrea",
    "flag_es","spain",
    "flag_et","ethiopia",
    "flag_fi","finland",
    "flag_fj","fiji",
    "flag_fk","falkland_islands_(malvinas)",
    "flag_fm","micronesia",
    "flag_fo","faroe_islands",
    "flag_fr","france",
    "flag_ga","gabon",
    "flag_gb","united_kingdom",
    "flag_gd","grenada",
    "flag_ge","georgia",
    "flag_gf","french_guiana",
    "flag_gg","guernsey",
    "flag_gh","ghana",
    "flag_gi","gibraltar",
    "flag_gl","greenland",
    "flag_gm","gambia",
    "flag_gn","guinea",
    "flag_gp","guadeloupe",
    "flag_gq","equatorial_guinea",
    "flag_gr","greece",
    "flag_gs","south_georgia",
    "flag_gt","guatemala",
    "flag_gu","guam",
    "flag_gw","guinea-bissau",
    "flag_gy","guyana",
    "flag_hk","hong_kong",
    "flag_hm","heard_island_and_mcdonald_islands",
    "flag_hn","honduras",
    "flag_hr","croatia",
    "flag_ht","haiti",
    "flag_hu","hungary",
    "flag_id","indonesia",
    "flag_ie","ireland",
    "flag_il","israel",
    "flag_im","isle_of_man",
    "flag_in","india",
    "flag_io","british_indian_ocean_territory",
    "flag_iq","iraq",
    "flag_ir","iran",
    "flag_is","iceland",
    "flag_it","italy",
    "flag_je","jersey",
    "flag_jm","jamaica",
    "flag_jo","jordan",
    "flag_jp","japan",
    "flag_ke","kenya",
    "flag_kg","kyrgyzstan",
    "flag_kh","cambodia",
    "flag_ki","kiribati",
    "flag_km","comoros",
    "flag_kn","saint_kitts_and_nevis",
    "flag_kp","north_korea",
    "flag_kr","south_korea",
    "flag_kw","kuwait",
    "flag_ky","cayman_islands",
    "flag_kz","kazakhstan",
    "flag_la","lao_people's_democratic_republic",
    "flag_lb","lebanon",
    "flag_lc","saint_lucia",
    "flag_li","liechtenstein",
    "flag_lk","sri_lanka",
    "flag_lr","liberia",
    "flag_ls","lesotho",
    "flag_lt","lithuania",
    "flag_lu","luxembourg",
    "flag_lv","latvia",
    "flag_ly","libya",
    "flag_ma","morocco",
    "flag_mc","monaco",
    "flag_md","moldova",
    "flag_me","montenegro",
    "flag_mf","saint_martin_(french_part)",
    "flag_mg","madagascar",
    "flag_mh","marshall_islands",
    "flag_mk","macedonia",
    "flag_ml","mali",
    "flag_mm","myanmar",
    "flag_mn","mongolia",
    "flag_mo","macao",
    "flag_mp","northern_mariana_islands",
    "flag_mq","martinique",
    "flag_mr","mauritania",
    "flag_ms","montserrat",
    "flag_mt","malta",
    "flag_mu","mauritius",
    "flag_mv","maldives",
    "flag_mw","malawi",
    "flag_mx","mexico",
    "flag_my","malaysia",
    "flag_mz","mozambique",
    "flag_na","namibia",
    "flag_nc","new_caledonia",
    "flag_ne","niger",
    "flag_nf","norfolk_island",
    "flag_ng","nigeria",
    "flag_ni","nicaragua",
    "flag_nl","netherlands",
    "flag_no","norway",
    "flag_np","nepal",
    "flag_nr","nauru",
    "flag_nu","niue",
    "flag_nz","new_zealand",
    "flag_om","oman",
    "flag_pa","panama",
    "flag_pe","peru",
    "flag_pf","french_polynesia",
    "flag_pg","papua_new_guinea",
    "flag_ph","philippines",
    "flag_pk","pakistan",
    "flag_pl","poland",
    "flag_pm","saint_pierre_and_miquelon",
    "flag_pn","pitcairn",
    "flag_pr","puerto_rico",
    "flag_ps","palestinian_territory",
    "flag_pt","portugal",
    "flag_pw","palau",
    "flag_py","paraguay",
    "flag_qa","qatar",
    "flag_re","réunion",
    "flag_ro","romania",
    "flag_rs","serbia",
    "flag_ru","russia",
    "flag_rw","rwanda",
    "flag_sa","saudi_arabia",
    "flag_sb","solomon_islands",
    "flag_sc","seychelles",
    "flag_sd","sudan",
    "flag_se","sweden",
    "flag_sg","singapore",
    "flag_sh","saint_helena,_ascension_and_tristan_da_cunha",
    "flag_si","slovenia",
    "flag_sj","svalbard_and_jan_mayen",
    "flag_sk","slovakia",
    "flag_sl","sierra_leone",
    "flag_sm","san_marino",
    "flag_sn","senegal",
    "flag_so","somalia",
    "flag_sr","suriname",
    "flag_ss","south_sudan",
    "flag_st","sao_tome_and_principe",
    "flag_sv","el_salvador",
    "flag_sx","sint_maarten_(dutch_part)",
    "flag_sy","syrian_arab_republic",
    "flag_sz","swaziland",
    "flag_tc","turks_and_caicos_islands",
    "flag_td","chad",
    "flag_tf","french_southern_territories",
    "flag_tg","togo",
    "flag_th","thailand",
    "flag_tj","tajikistan",
    "flag_tk","tokelau",
    "flag_tl","timor-leste",
    "flag_tm","turkmenistan",
    "flag_tn","tunisia",
    "flag_to","tonga",
    "flag_tr","turkey",
    "flag_tt","trinidad_and_tobago",
    "flag_tv","tuvalu",
    "flag_tw","taiwan",
    "flag_tz","tanzania",
    "flag_ua","ukraine",
    "flag_ug","uganda",
    "flag_um","united_states_minor_outlying_islands",
    "flag_us","united_states",
    "flag_uy","uruguay",
    "flag_uz","uzbekistan",
    "flag_va","vatican_city",
    "flag_vc","saint_vincent_and_the_grenadines",
    "flag_ve","venezuela",
    "flag_vg","virgin_islands,_british",
    "flag_vi","virgin_islands,_u.s.",
    "flag_vn","viet_nam",
    "flag_vu","vanuatu",
    "flag_wf","wallis_and_futuna",
    "flag_ws","samoa",
    "flag_ye","yemen",
    "flag_yt","mayotte",
    "flag_za","south_africa",
    "flag_zm","zambia",
    "flag_zw","zimbabwe",
    "banana", "rotate",
    "carrot",
    "toamto", "totma", "tomat", "toa", "tomato", "fruit",
    "cery", "cherry",
    "spicy", "spicy_pepper", "pepper",
    "beans",
    "strawberry", "celeste",
    "apple",
    "bento", "bento_box",
    "sushi", "roll",
    "rice_ball", "onigiri",
    "ramen", "soup",
    "potato",
    "waffle",
    "plate",
    "pumpkin",
    "pizza", "pizzer",
    "bread", "loaf",
    "bread2", "bread_slice",
    "cookie",
    "cookie_crumb",
    "burger",
    "meat",
    "egg", "egg_irl",
    "cake", "lie",
    "coffee", "cafe", "cofve",
    "juice", "juicebox",
    "lolipop",
    "icecream", "ice_cream",
    "cheese", "big_cheese",
    "popcorn",
    "heart_hands",
    "+1", "thumbs_up",
    "-1", "thumbs_down",
    "wave",
    "hand",
    "okay",
    "nailcare",
    "pray", "prayers",
    "handshake", "help",
    "middle_finger", "fuck_you",
    "l", "l_hand", "loser", "point_up",
    "strong", "muscle", "arm",
    "this", "point_up",
    "foot",
    "leg",
    "clap",
    "heart_red", "red_heart", "<3",
    "heart_orange", "orange_heart",
    "heart_yellow", "yellow_heart",
    "heart_green", "green_heart",
    "heart_blue", "blue_heart",
    "heart_purple", "purple_heart",
    "heart_brown", "brown_heart",
    "heart_black", "black_heart",
    "heart_white", "white_heart",
    "heart_pink", "pink_heart",
    "heart_skye", "skye_heart",
    "heart_kiri", "kiri_heart",
    "heart_nuke", "nuke_heart",
    "heart_nick", "nick_heart",
    "heart_foxes", "foxes_heart",
    "heart_on_fire", "fire_heart",
    "heart_broken", "broken_heart", "</3",
    "mending_heart", "heart_mending",
    "gift_heart", "heart_gift",
    "heart_sparkling", "sparkling_heart",
    "regional_indicator_a", "letter_a",
    "regional_indicator_b", "letter_b",
    "regional_indicator_c", "letter_c",
    "regional_indicator_d", "letter_d",
    "regional_indicator_e", "letter_e",
    "regional_indicator_f", "letter_f",
    "regional_indicator_g", "letter_g",
    "regional_indicator_h", "letter_h",
    "regional_indicator_i", "letter_i",
    "regional_indicator_j", "letter_j",
    "regional_indicator_k", "letter_k",
    "regional_indicator_l", "letter_l",
    "regional_indicator_m", "letter_m",
    "regional_indicator_n", "letter_n",
    "regional_indicator_o", "letter_o",
    "regional_indicator_p", "letter_p",
    "regional_indicator_q", "letter_q",
    "regional_indicator_r", "letter_r",
    "regional_indicator_s", "letter_s",
    "regional_indicator_t", "letter_t",
    "regional_indicator_u", "letter_u",
    "regional_indicator_v", "letter_v",
    "regional_indicator_w", "letter_w",
    "regional_indicator_x", "letter_x",
    "regional_indicator_y", "letter_y",
    "regional_indicator_z", "letter_z",
    "number_0", "zero",
    "number_1", "one",
    "number_2", "two",
    "number_3", "three",
    "number_4", "four",
    "number_5", "five",
    "number_6", "six",
    "number_7", "seven",
    "number_8", "eight",
    "number_9", "nine",
    "number_10", "ten", "keycap_ten",
    "asterisk",
    "visual_studio_code", "vscode",
    "sublime_text",
    "notepad++",
    "notepad",
    "aseprite", "ase",
    "paitn_dot_net", "pdn",
    "blockbench",
    "steam",
    "quilt",
    "fabric",
    "forge",
    "modrinth",
    "intellij",
    "visual_studio",
    "eclipse_ide",
    "lua",
    "java",
    "c",
    "python",
    "whatsapp", 
    "mastodon",
    "discord",
    "twitter",
    "mcdonalds",
    "tacobell",
    "exploit",
    "troll", "trol",
    "stonks", "stock", "trade", "stock_market",
    "no_stonks",
    "smooth_brain",
    "shrek", "ogre",
    "rick_astley_feet", "rickroll", "rick", "never_gonna_give_you_up",
    "loss",
    "arthur_fist",
    "missing", "missingno", "cs_source", "no_texture",
    "catstare", "cat_stare",
    "pregnant_man", "man",
    "pregnant_woman", "woman",
    "pregnant_person", "person",
    "man",
    "woman",
    "person",
    "moon", "crescent_moon",
    "moon2", "full_moon",
    "sparkles",
    "lightning", "thunder", "zap",
    "poof",
    "fire", "fire1", "fire_red",
    "fire3", "fire_blue",
    "fire2", "fire_green",
    "hi_im_new", "plant",
    "flower", "daisy",
    "mercury", "planet_mercury",
    "venus", "planet_venus",
    "earth", "planet_earth",
    "mars", "planet_mars",
    "jupiter", "planet_jupiter",
    "saturn", "planet_saturn",
    "uranus", "planet_uranus",
    "neptune", "planet_neptune",
    "pluto", "planet_pluto",
    "brain",
    "anatomical_heart",
    "camera", "4k",
    "sax", "saxophone",
    "chess", "pawn",
    "moyai",
    "spoon", "zerok", "iron_shovel",
    "spork", "spunk",
    "fork", "twork",
    "fork_and_knife", "forknife", "fork_knife", "twork_onek",
    "mega", "megaphone",
    "loud", "speaker",
    "piano", "keyboard",
    "cassette", "music_tape", "tape", "sound_tape",
    "cd", "disc",
    "hammer_big",
    "golden_hammer", "hellper",
    "feather",
    "magic_wand", "wand", "magic",
    "gun", "water_gun",
    "scissors",
    "baseball_bat", "baseball",
    "hammer",
    "axe",
    "firecracker", "dynamite",
    "tada", "party_popper",
    "knife", "stab", "murder",
    "wrench", "tool",
    "lantern", "paper_lantern", "izakaya_lantern", "lamp", "lämp",
    "yarn",
    "crown",
    "fez",
    "witch_hat", "witch",
    "mechanical_leg","robot_leg",
    "grave", "ded",
    "balloon",
    "white_ribbon", "cancer_lung", "lung_cancer",
    "pink_ribbon", "cancer_breast", "breast_cancer",
    "money", "usd",
    "key",
    "koinobori", "flags",
    "mechanical_arm", "robot_arm",
    "racecar", "vroom",
    "ambulance",
    "truck", "trailer",
    "wheel",
    "candle", "wick",
    "timer", "stopwatch",
    "boom", "explosion",
    "rocket",
    "pencil",
    "scroll",
    "basketball",
    "@skye", "@skyrina",
    "@ame", "@lumelia",
    "@chloe", "@chloespacedout",
    "@kate", "@lexize",
    "@slime_deni", "@circlemaniac",
    "@slime_gwape", "@gwape",
    "@gn","@gnamimates",
    "@scarlet","@scarletlight",
    "@kiri", "@karma",
    "@electric", "@ohitselectric",
    "@palck",
    "@serena",
    "@toast",
    "@slyme",
    "@perry","@aster",
    "@jepril",
    "@jonkkusa",
    "@kye", "@cookie", "@kylie",
    "@forseir",
    "@katt", "@kitkat",
    "@auria", "@dragekk",
    "@syl", "@sylvia",
    "@4p5",
    "@4p5_hair",
    "@tsuki", "@zqukiiruhkih", "@zqukiiruh'kih",
    "@tsuki_ramen",
    "@crimson", "@kelvin",
    "@josh", "@joshakabane",
    "@josh-naga", "@joshakabane-naga",
    "@josh-galactus", "@galactus-prime",
    "@maven",
    "@maven-logo",
    "@cone","@mxduck",
    "@april","@kenopsia",
    "@cosmic","@cosmiccalamitty","@rio1u",
    "pride_agender", "agender",
    "pride_aroace", "aroace",
    "pride_aromantic", "aro",
    "pride_asexual", "ace",
    "pride_bigender", "bigender",
    "pride_bisexual", "bi", "bisexual",
    "pride_demiboy", "demiboy",
    "pride_demigender", "demigender",
    "pride_demigirl", "demigirl",
    "pride_demiromantic", "demiromantic",
    "pride_demisexual", "demisexual",
    "pride_disability", "disability",
    "pride_finsexual", "finsexual",
    "pride_gaymen", "gay1",
    "pride_genderfae", "genderfae",
    "pride_genderfluid", "genderfluid",
    "pride_genderqueer", "genderqueer",
    "pride_intersex", "intersex",
    "pride_lesbian", "gay2", "lesbian",
    "pride_nonbinary", "nonbinary", "nb",
    "pride_pansexual", "pan",
    "pride_plural", "plural",
    "pride_polysexual", "poly", "polysexual",
    "pride", "gay",
    "pride_transgender", "pride_trans", "transgender", "trans",
    "amongus", "among", "sus", "imposter",
    "amongus_dead", "among_dead", "sus_dead", "imposter_dead",
    "sonic", "sanic", "gottagofast",
    "hollow_knight",
    "doom_slayer", "slayer_mark",
    "kirby",
    "king_deedeedee",
    "m_tomato",
    "rare_candy",
    "lopunny",
    "spiffo",
    "baba", "baba_is_you",
    "hämis", "hamis", "noita",
    "vbucks", "fortnite",
    "v1", "ultrakill",
    "r6_mute",
    "nether", "nether_portal",
    "minecraft_sun", "minceraft_sun",
    "minecraft_moon", "minceraft_moon",
    "creeper",
    "conductor", "merder", "peckneck",
    "snatcher", "foooool",
    "timepiece",
    "hat_kid", "a_hat_in_time",
    "sandopede1",
    "sandopede2",
    "sandopede3",
    "sandopede4",
    "sandopede5",
    "strabby",
    "bunger",
    "bunger_bbq",
    "uno_select_color", "uno_card", "uno_wild",
    "uno_take_2", "+2", "uno_draw_2",
    "uno_take_4", "+4", "uno_draw_4",
    "uno_reverse", "no_u",
    "uno_skip",
    "karma_1", "karma_wrath",
    "karma_2", "karma_lust",
    "karma_3", "karma_attachment",
    "karma_4", "karma_gluttony",
    "karma_5", "karma_self_preservation",
    "karma_10", "karma_max",
    "looks_to_the_moon", "lttm",
    "pou", "dirty_pou",
    "tbh", "autism_creature", "yippe",
    "bloon_red",
    "bloon_blue",
    "bloon_green",
    "bloon_yellow",
    "bloon_pink",
    "bloon_black",
    "bloon_white",
    "bloon_purple",
    "bloon_lead",
    "bloon_zebra",
    "bloon_rainbow",
    "bloon_ceramic",
    "bloon_moab", "moab",
    "bloon_bfb", "bfb",
    "bloon_zomg", "zomg",
    "bloon_ddt", "ddt",
    "bloon_bad", "bad",
    "bloons_banana_farm",
    "bloons_dart_monkey", "monkey",
    "boss_bloonarius",
    "boss_lych",
    "boss_vortex",
    "boss_dreadbloon",
    "adofai", "a_dance_of_fire_and_ice",
    "tf2", "team_fortress_2",
    "factorio",
    "gmod", "garrys_mod", "garry's_mod",
    "csgo", "counter_strike", "counterstrik",
    "rust",
    "terraria",
    "slime_rancher", "pink_slime",
    "omori", "omor",
    "minecraft", "grass_block",
    "enter_the_gungeon", "bulletkin",
    "undertale",
    "deltarune",
    "rain_world", "rainworld", "slugcat", "goober",
    "pac_man", "pacman",
    "ghost_red", "blinky",
    "ghost_pink", "pinky",
    "ghost_blue", "inky",
    "ghost_orange", "clyde",
    "ghost_dead",
    "ghost_vulnerable",
    "space_invader1",
    "space_invader2",
    "space_invader3",
    "space_invader4",
    "space_invader5",
    "space_invader6",
    "space_invader7",
    "space_invader8",
    "tm", "trademark",
    "infinity", "symbol_infinity",
    "wheelchair", "symbol_wheelchair",
    "parking", "symbol_parking",
    "info", "information", "symbol_info", "symbol_information",
    "warning", "symbol_warning",
    "red", "symbol_octaganal",
    "cancel", "symbol_cancel",
    "volume_0", "volume_mute", "mute",
    "volume_1",
    "volume_2",
    "volume_3",
    "brightness_low",
    "brightness_high",
    "cursor_1", "mouse_1",
    "cursor_2", "mouse_2",
    "network1", "ping1", "asian_ping",
    "network2", "ping2", "eu_ping",
    "network3", "ping3", "sa_ping",
    "network4", "ping4", "na_ping",
    "www", "globe", "internet",
    "music1", "note_beamed",
    "music2",
    "speech_bubble", "texting", "typing",
    "checkmark",
    "x",
    "no_entry", "cancel",
    "circle",
    "underage", "18+", "nsfw",
    "no_smoking", "smoking",
    "paw", "furry",
    "zzz",
    "exclamation", "_!",
    "question", "_?",
    "bangbang", "!!",
    "interrobang", "!?",
    "hot", "sauna", "hotsprings", "symbol_hot",
    "anger",
    "100",
    "alteration", "alteration_mark", "part_alteration_mark",
    "a", "blood_a",
    "b", "blood_b",
    "ab", "blood_ab",
    "o", "blood_o",
    "cl", "blood_cl",
    "fleur_de_lis",
    "trident",
    "yin_yang",
    "clock12", "0h", "12h", "12am", "12pm",
    "clock1", "1h", "13h", "1am", "1pm",
    "clock2", "2h", "14h", "2am", "2pm",
    "clock3", "3h", "15h", "3am", "3pm",
    "clock4", "4h", "16h", "4am", "4pm",
    "clock5", "5h", "17h", "5am", "5pm",
    "clock6", "6h", "18h", "6am", "6pm",
    "clock7", "7h", "19h", "7am", "7pm",
    "clock8", "8h", "20h", "8am", "8pm",
    "clock9", "9h", "21h", "9am", "9pm",
    "clock10", "10h", "22h", "10am", "10pm",
    "clock11", "11h", "23h", "11am", "11pm",
    "hug", "hugs",
    "speak", "person_speaking", "head_speaking",
    "bust", "bust_in_sillouette",
    "busts", "busts_in_sillouette",
    
}

function pings.set_speechBubble(visible)
    chatVis = visible
end

function pings.set_Slash(bool)
    slash = bool
end
function pings.set_Emoji(toggle, emojiString)
    emojiBool = toggle
    emoji = emojiString
end

local chatSend = keybinds:newKeybind("(Only used to check for when things are sent in chat)", "key.keyboard.enter", false)
models.modules.speech_bubble.speechBubble.Camera_speech:setVisible(true)
local SentMsgMover = models.modules.speech_bubble.speechBubble.Camera_speech:newPart("SentMsgMover")
local SentChatMsg
SentChatMsg = SentMsgMover:newText("SentChatMsg")
function pings.ChatSend(text)
    if text ~= "" or nil then
        SentChatMsg:setLight(15)
        SentChatMsg:setVisible(true)
        SentChatMsg:setText(text)
        SentChatMsg:setAlignment("CENTER")
        textVisibility = textVisibility + 1
        textPosCorrect = false
        sounds:playSound("minecraft:entity.fox.ambient", player:getPos(), 1, 1.2, false)
        wait(100, pings.ChatTextGon)
    end
end

function pings.ChatTextGon()
    textVisibility = textVisibility - 1
end

function events.tick()
    if chatVis ~= host:isChatOpen() then
        pings.set_speechBubble(host:isChatOpen()) 
    end
    if host:isChatOpen() then slash = string.sub(host:getChatText(),1,1) == "/" end
    if syncedSlash ~= slash then
        pings.set_Slash(slash)
        syncedSlash = slash
    end
    if host:isChatOpen() then emoji = host:getChatText():match(":([%w_][%w_]-):") else emoji = nil end
    if host:isChatOpen() and emoji ~= nil then emoji = ":"..emoji..":" end
    if emojiStored ~= emoji then
        emojiStored = emoji
        emojiBool = false
        for i, emojiCheck in ipairs(ValidEmojis) do
            if host:isChatOpen() and host:getChatText():match(":([%w_][%w_]-):") ~= ValidEmojis[i] then
                emojiBool = false 
            elseif host:isChatOpen() and host:getChatText():match(":([%w_][%w_]-):") == emojiCheck then emojiBool = true
            return end
        end
        pings.set_Emoji(emojiBool, emoji)
    end
    if host:isChatOpen() then chatText = host:getChatText() end
    if host:isChatOpen() ~= chatCheck then
        if chatCheck and not slash then chatSend.press = pings.ChatSend(chatText) end
        chatCheck = host:isChatOpen()
    end
    if not host:isChatOpen() then
        slash = false
    end

end

function events.render(delta)

local speech_bubble = models.modules.speech_bubble.speechBubble.Camera_speech:newSprite("speechBubble"):setTexture(textures['modules.speech_bubble.speech_bubble'])
:setPos(14,4 + math.round(math.sin((world:getTime()+delta)/14)/1,0)/2)
:setLight(15)
:setVisible(chatVis)
local speech_dot1 = models.modules.speech_bubble.speechBubble.Camera_speech:newSprite("dot1"):setTexture(textures['modules.speech_bubble.dot'])
:setPos(12.5 - (slash and 1.5 or 0),2 - (slash and 0.5 or 0) + math.round(math.sin((world:getTime()+delta)/4)/1.5)/4 + math.round(math.sin((world:getTime()+delta)/14)/1,-0.01)/2)
:setLight(15):setScale(slash and 0.7 or 1)
:setVisible(chatVis and not emojiBool)
local speech_dot2 = models.modules.speech_bubble.speechBubble.Camera_speech:newSprite("dot2"):setTexture(textures['modules.speech_bubble.dot'])
:setPos(10.5 - (slash and 1 or 0),2 - (slash and 0.5 or 0) + math.round(math.sin((world:getTime()+delta)/4 + 0.6666)/1.5)/4 + math.round(math.sin((world:getTime()+delta)/14)/1,-0.01)/2)
:setLight(15):setScale(slash and 0.7 or 1)
:setVisible(chatVis and not emojiBool)
local speech_dot3 = models.modules.speech_bubble.speechBubble.Camera_speech:newSprite("dot3"):setTexture(textures['modules.speech_bubble.dot'])
:setPos(8.5 - (slash and 0.5 or 0),2 - (slash and 0.5 or 0) + math.round(math.sin((world:getTime()+delta)/4 + 1.3333)/1.5)/4 + math.round(math.sin((world:getTime()+delta)/14)/1,-0.01)/2)
:setLight(15):setScale(slash and 0.7 or 1)
:setVisible(chatVis)
local speech_slash = models.modules.speech_bubble.speechBubble.Camera_speech:newSprite("slash"):setTexture(textures['modules.speech_bubble.slash'])
:setPos(13,3 + (math.round(math.sin((world:getTime()+delta)/14)/1,-0.01)/2)):setScale(0.7):setLight(15):setVisible(slash)
local speech_emoji = models.modules.speech_bubble.speechBubble.Camera_speech:newText("EmojiText")
:setPos(12.8,3 + (math.round(math.sin((world:getTime()+delta)/14)/1,-0.01)/2), -0.1):setScale(0.5):setLight(15):setVisible(emojiBool):setText(emoji)

models.modules.speech_bubble.speechBubble.Camera_speech:setPos(0,math.sin((world:getTime()+delta)/7)/3,0)

if textVisibility == 0 then 
    SentChatMsg:setScale(math.lerp(SentChatMsg:getScale(), 0, delta/4))
    SentChatMsg:setPos(math.lerp(SentChatMsg:getPos(), vec(0, 5, 0), delta/4))
    SentChatMsg:setOpacity(math.lerp(SentChatMsg:getOpacity(), 0, delta/3))
end
if textVisibility > 0 then
    SentChatMsg:setScale(math.lerp(SentChatMsg:getScale(), 0.75, delta/2))
    if SentChatMsg:getPos() >= vec(0, 19, 0) then textPosCorrect = true end
    if not textPosCorrect then
        SentChatMsg:setPos(math.lerp(SentChatMsg:getPos(), vec(0, 20, 0), delta/2))
    else
        SentChatMsg:setPos(0,20 + math.round(math.sin((world:getTime()+delta)/10)/0.5,0)/4, 0)
    end
    SentChatMsg:setOpacity(math.lerp(SentChatMsg:getOpacity(), 1, delta/4))
end
if textVisibility < 0 then textVisibility = 0 end

end